url: "https://pyconjp-2025-chair.nishimotz.com/"
baseurl: ""
title: "PyCon JP 2025 座長の日報"
author: "nishimotz"
description: "PyCon JP 2025 は2025年9月26日・27日に広島で開催されます。"
future: true
plugins:
  - jekyll-postcss
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true